excerpt_separator: ""
markdown: kramdown
url: http://estadoperfecto.github.io
title: El Estado Perfecto
tagline: Notas breves sobre un estado perfecto
description: El estado perfecto y el camino a su consecución
paginate: 5
